FROM node:24-alpine3.22 as build

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

WORKDIR /app
COPY . .

RUN npm ci
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN npm run build

FROM node:24-alpine3.22 as production
ENV NODE_ENV=production
WORKDIR /usr/share/webapps/app
COPY --from=build /app/dist .
RUN npm install -g serve

EXPOSE 80

CMD ["serve", "-s", ".", "-l", "80"]